apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-cluster
spec:
  serviceName: mariadb
  replicas: 3
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "master"
        - name: MYSQL_DATABASE
          value: "DevopsDatabase"
